### ISSUE TITLE
New Podcast 

### ISSUE THREAD

**Issue by MatBenfield** [MatBenfield/TheChels.uk#349]
```yaml
-
  category: Finance
  link: "https://play.acast.com/s/ftadviser"
  name: "FT Adviser"
```
