### ISSUE TITLE
New Podcast

### ISSUE THREAD

**Issue by MatBenfield** [MatBenfield/TheChels.uk#363]
```yaml
-
  category: News
  link: "https://feeds.npr.org/510351/podcast.xml"
  name: "NPR - Short Wave"
```
