### ISSUE TITLE
New Podcast

### ISSUE THREAD

**Issue by MatBenfield** [MatBenfield/TheChels.uk#364]
```yaml
-
  category: Security
  link: "https://opensourcesecuritypodcast.libsyn.com/rss"
  name: "Open Source Security Podcast"
```
