### ISSUE TITLE
New Podcast

### ISSUE THREAD

**Issue by MatBenfield** [MatBenfield/TheChels.uk#368]
```yaml
-
  category: Work
  link: "https://feeds.pacific-content.com/workcheck"
  name: "Atlassian - Work Check"
```
