### ISSUE TITLE
New Podcast

### ISSUE THREAD

**Issue by MatBenfield** [MatBenfield/TheChels.uk#372]
```yaml
-
  category: Finance
  link: "https://feeds.buzzsprout.com/1723086.rss"
  name: "Money Unfiltered"
```
