### ISSUE TITLE
New Podcast

### ISSUE THREAD

**Issue by MatBenfield** [MatBenfield/TheChels.uk#375]
```yaml
-
  category: Business
  link: "https://anchor.fm/s/1f843e50/podcast/rss"
  name: "Naked - by The Future Farm"
```
