### ISSUE TITLE
autolock

### ISSUE THREAD

**Issue by MatBenfield** [MatBenfield/TheChels.uk#384]
````yaml
---
name: Autolock
"on":
  schedule:
    # Run weekly, every Monday at 8:43.
    - cron: "43 8 * * 1"

jobs:

  autolock:
    uses: kdeldycke/workflows/.github/workflows/autolock.yaml@v1.1.0
    ```
    
https://github.com/kdeldycke/workflows/blob/main/.github/workflows/autolock.yaml
