### ISSUE TITLE
New Podcast: 

### ISSUE THREAD

**Issue by MatBenfield** [MatBenfield/TheChels.uk#387]
### Add Data

```yaml
-
   category:Finance
   link: "https://feeds.libsyn.com/83359/rss"
   name: "NextGen Planners"
```
